package sopc2dts.generators;

import java.util.Vector;

import sopc2dts.lib.BoardInfo;
import sopc2dts.lib.SopcInfoConnection;
import sopc2dts.lib.SopcInfoSystem;
import sopc2dts.lib.components.SopcInfoComponent;
import sopc2dts.lib.components.SopcInfoInterface;
import sopc2dts.lib.components.SopcInfoMemoryBlock;

public class DTSGenerator extends AbstractSopcGenerator {
	Vector<SopcInfoComponent> vHandled = new Vector<SopcInfoComponent>();
	public DTSGenerator(SopcInfoSystem s) {
		super(s);
	}

	@Override
	public String getExtension() {
		return "dts";
	}

	@Override
	public String getOutput(BoardInfo bi) {
		return getOutput(bi, SopcInfoComponent.parameter_action.NONE);
	}
	public String getOutput(BoardInfo bi, SopcInfoComponent.parameter_action paramAction) {
		int indentLevel = 0;
		vHandled.clear();
		String res = "/*\n"
			+ " * This devicetree is generated by sopc2dts\n"
			+ " * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>\n"
			+ " * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>\n"
			+ " */\n"
			+ "/dts-v1/;\n"
			+ "/ {\n"
			+ indent(++indentLevel) + "model = \"ALTR," + sys.getSystemName() + "\";\n"
			+ indent(indentLevel) + "compatible = \"ALTR," + sys.getSystemName() + "\";\n"
			+ indent(indentLevel) + "#address-cells = <1>;\n"
			+ indent(indentLevel) + "#size-cells = <1>;\n"
			+ getDTSCpus(bi, paramAction, indentLevel);
		
		SopcInfoComponent povComp = getComponentByName(bi.getPov());
		if(povComp!=null)
		{
			res += getDTSMemoryFrom(bi, povComp, indentLevel);
			res += indent(indentLevel++) + "sopc@0 {\n" +
					indent(indentLevel) + "#address-cells = <1>;\n" +
					indent(indentLevel) + "#size-cells = <1>;\n" +
					indent(indentLevel) + "device_type = \"soc\";\n" +
					indent(indentLevel) + "compatible = \"ALTR,avalon\",\"simple-bus\";\n" +
					indent(indentLevel) + "ranges ;\n" +
					indent(indentLevel) + "bus-frequency = < " + povComp.getClockRate() + " >;\n";
			res += getDTSBusFrom(bi, povComp, paramAction, indentLevel);
			res += indent(--indentLevel) + "}; //sopc\n";
		}
		res += getDTSChosen(bi, paramAction, indentLevel);
		return res;
	}
	String getDTSChosen(BoardInfo bi, 
			SopcInfoComponent.parameter_action paramAction, int indentLevel)
	{
		String res = "";
		if((bi.getBootArgs()==null)||(bi.getBootArgs().length()==0))
		{
			bi.setBootArgs("debug console=ttyAL0,115200");
		} else {
			bi.setBootArgs(bi.getBootArgs().replaceAll("\"", ""));
		}
		res += indent(indentLevel++) + "chosen {\n" +
				indent(indentLevel) + "bootargs = \"" + bi.getBootArgs() + "\";\n" +
				indent(--indentLevel) + "};\n";
		res += indent(--indentLevel) + "};\n";
		return res;		
	}
	String getDTSCpus(BoardInfo bi, 
			SopcInfoComponent.parameter_action paramAction, int indentLevel)
	{
		int numCPUs = 0;
		String res="";
		for(SopcInfoComponent comp : sys.getSystemComponents())
		{
			if(comp.getScd().getGroup().equalsIgnoreCase("cpu"))
			{
				if(numCPUs==0)
				{
					res += indent(indentLevel++) + "cpus {\n"
						+ indent(indentLevel) + "#address-cells = <1>;\n"
						+ indent(indentLevel) + "#size-cells = <0>;\n";
					if(bi.getPov()==null) {
						bi.setPov(comp.getInstanceName());
					}
				}
				comp.setAddr(numCPUs);
				res += comp.toDts(bi, indentLevel, paramAction);
				vHandled.add(comp);
				numCPUs++;
			}
		}
		if(numCPUs>0) {
			res += indent(--indentLevel) + "};\n";
		}
		return res;
	}
	String getDTSMemoryFrom(BoardInfo bi, SopcInfoComponent master, int indentLevel)
	{
		String res = "";
		
		if(master!=null)
		{
			Vector<String> vMemoryMapped = bi.getMemoryNodes();
			if(vMemoryMapped!=null)
			{
				for(SopcInfoInterface intf : master.getInterfaces())
				{
					if(intf.isMemoryMaster())
					{
						for(SopcInfoMemoryBlock mem : intf.getMemoryMap())
						{
							if(vMemoryMapped.contains(mem.getModule()))
							{
								SopcInfoComponent comp = getComponentByName(mem.getModule());
								if((comp!=null)&&(!vHandled.contains(comp)))
								{
									if(res.length()==0)
									{
										res = indent(indentLevel++) + "memory@0 {\n" +
												indent(indentLevel) + "device_type = \"memory\";\n" +
												indent(indentLevel) + "reg = <" + 
													String.format("0x%08X 0x%08X", mem.getBase(), mem.getSize());
									} else {
										res += "\n" + indent(indentLevel) + 
											String.format("\t0x%08X 0x%08X", mem.getBase(), mem.getSize());
									}
									vHandled.add(comp);
								}		
							}
						}
					}
				}
			}

			if(res.length()==0)
			{
				/*
				 * manual memory-map failed or is not present.
				 * Just list all devices classified as "memory"
				 */
				vMemoryMapped = new Vector<String>();
				for(SopcInfoInterface intf : master.getInterfaces())
				{
					if(intf.isMemoryMaster())
					{
						for(SopcInfoMemoryBlock mem : intf.getMemoryMap())
						{
							if(!vMemoryMapped.contains(mem.getModule()))
							{
								SopcInfoComponent comp = getComponentByName(mem.getModule());
								if(comp!=null)
								{
									if(comp.getScd().getGroup().equalsIgnoreCase("memory"))
									{
										if(res.length()==0)
										{
											res = indent(indentLevel++) + "memory@0 {\n" +
													indent(indentLevel) + "device_type = \"memory\";\n" +
													indent(indentLevel) + "reg = <" + 
														String.format("0x%08X 0x%08X", mem.getBase(), mem.getSize());
										} else {
											res += "\n" + indent(indentLevel) + 
												String.format("\t0x%08X 0x%08X", mem.getBase(), mem.getSize());
										}
										vMemoryMapped.add(mem.getModule());
										vHandled.add(comp);
									}
								}		
							}
						}
					}
				}
			}
			if(res.length()>0) {
				res += ">;\n" + indent(--indentLevel) + "};\n";
			}
		}
		return res;
	}

	String getDTSBusFrom(BoardInfo bi, SopcInfoComponent master, 
				SopcInfoComponent.parameter_action paramAction, int indentLevel)
	{
		String res = "";
		if(master!=null)
		{
			for(SopcInfoInterface intf : master.getInterfaces())
			{
				if(intf.isMemoryMaster())
				{
					res += indent(indentLevel) + "//Port " + intf.getName() + " of " + master.getInstanceName() + "\n";
					for(SopcInfoConnection conn : intf.getConnections())
					{
						SopcInfoComponent slave = conn.getSlaveModule();						
						if(slave!=null)
						{
							if(!vHandled.contains(slave))
							{
								res += slave.toDts(bi, indentLevel,paramAction, conn,false);
								vHandled.add(slave);
								if(slave.getScd().getGroup().equalsIgnoreCase("bridge"))
								{
									res += "\n" + getDTSBusFrom(bi, slave, paramAction, ++indentLevel);
									indentLevel--;
								}
								res += indent(indentLevel) + "}; //end "+slave.getScd().getGroup()+" (" + slave.getInstanceName() + ")\n\n";
							}
						}
					}
				}
			}
		}
		return res;
	}

	public SopcInfoComponent getComponentByName(String name)
	{
		for(SopcInfoComponent c : sys.getSystemComponents())
		{
			if(c.getInstanceName().equalsIgnoreCase(name))
			{
				return c;
			}
		}
		return null;
	}
}
